/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Boostable"): TruffleContracts.BoostableContract;
      require(name: "Dubiex"): TruffleContracts.DubiexContract;
      require(
        name: "DummyVanillaERC20"
      ): TruffleContracts.DummyVanillaERC20Contract;
      require(
        name: "DummyVanillaERC721"
      ): TruffleContracts.DummyVanillaERC721Contract;
      require(
        name: "EIP712Boostable"
      ): TruffleContracts.EIP712BoostableContract;
      require(name: "ERC165"): TruffleContracts.ERC165Contract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC721"): TruffleContracts.ERC721Contract;
      require(name: "ERC721Holder"): TruffleContracts.ERC721HolderContract;
      require(
        name: "IBoostableERC20"
      ): TruffleContracts.IBoostableERC20Contract;
      require(name: "IERC165"): TruffleContracts.IERC165Contract;
      require(
        name: "IERC1820Registry"
      ): TruffleContracts.IERC1820RegistryContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IERC721"): TruffleContracts.IERC721Contract;
      require(
        name: "IERC721Enumerable"
      ): TruffleContracts.IERC721EnumerableContract;
      require(
        name: "IERC721Metadata"
      ): TruffleContracts.IERC721MetadataContract;
      require(
        name: "IERC721Receiver"
      ): TruffleContracts.IERC721ReceiverContract;
      require(name: "IOptIn"): TruffleContracts.IOptInContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
    }
  }
}
